version: '3'
services:
  orientdb:
    image: "orientdb:latest"
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: 'root'
    volumes:
      - ./config:/orientdb/config
      - ./databases:/orientdb/databases
      - ./backup:/orientdb/backup
